Resources:
  # Cognito - User pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.app}_${self:custom.service_acronym}_${self:custom.stage}_user_pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
        InviteMessageTemplate:
          EmailMessage: "Your username is {username} and your verification code: {####}. Please provide it inside the application."
          EmailSubject: "Your verification code to Flowcontrol service"
          SMSMessage: "Your username is {username} and temporary password is {####}. "
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies: 
        PasswordPolicy:
          MinimumLength : 10
          TemporaryPasswordValidityDays: 7
      #AliasAttributes:
      #  - email
      # Schema:
      #   - Name: email
      #     AttributeDataType: String
      #     Mutable: false
      #     Required: true

  # Cognito - Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.app}_${self:custom.service_acronym}_${self:custom.stage}_cognito_client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

  #https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-authorizer
  CognitoUserPoolAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: ${self:custom.cognito_authorizer}
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs:
        - Fn::GetAtt: [CognitoUserPool, Arn]

  ApiGatewayRestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: ${self:custom.app}_${self:custom.service_acronym}_${self:custom.stage}_apigateway_restapi
      EndpointConfiguration:
        Types:
          - EDGE

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient

  UserPoolAuthorizer:
    Value:
      Ref: CognitoUserPoolAuthorizer

  UserPoolArn:
    Value:
      "Fn::GetAtt": [CognitoUserPool, Arn]
