Resources:
  ClientDataProviderRoleAddClient:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: flowcontrol-clientdataprovider-dynamodb-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:PutItem
                Resource:
                  - "*"

  ClientDataProviderRoleCheckLicense:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: flowcontrol-clientdataprovider-dynamodb-cognito-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - cognito-idp:AdminListGroupsForUser
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminRemoveUserFromGroup
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                Resource:
                  - "*"

  RoleForAdminUpdate:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: flowcontrol-clientdataprovider-cognito-s3-update-files-${self:custom.stage}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - lambda:ListFunctions
                  - lambda:InvokeFunction
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:PutObject
                Resource: 
                  - arn:aws:s3:::flowcontrol-clientdataprovider-private-bucket
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::flowcontrol-aws-integration-public-objects-dev
                  
  RoleForClientDownload:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: flowcontrol-clientdataprovider-s3-download-files-${self:custom.stage}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - lambda:ListFunctions
                  - lambda:InvokeFunction
                Resource:
                  - "*"
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: 
                  - arn:aws:s3:::flowcontrol-clientdataprovider-private-bucket
              
  
